export const brandsArray = [
'Buick',
        'Volvo',
        'Hummer',
        'Subaru',
        'Mitsubishi',
        'Nissan',
        'Lincoln',
        'GMC',
        'Ford',
        'Honda',
        'Acura',
        'Chevrolet',
        'MINI',
        'Bentley',
        'JEEP',
        'Audi',
        'BMW',
        'Mercedes-Benz',
        'Chrysler',
        'Kia',
        'Land Rover',
]